# Operating system (build VM template)
os: Windows Server 2019

# If the build configuration does not specify build worker image
# then Visual Studio 2015 image is used.
image: Visual Studio 2019

# Restrict to Git branches below
branches:
  only:
    - master

# Scripts that run after cloning repository
install:
  - dotnet restore

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

# Cache files until appveyor.yml is modified.
cache:
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
  - '%Userprofile%\.nuget\packages' # NuGet

# Run scripts below before
before_build:
  - where dotnet

# To run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: dotnet pack

# NuGet files qualified as artifacts
artifacts:
  - path: 'dist\**\*.nupkg' # find the NuGet files
    name: NuGet_Files

# Deploy to GitHub releases
deploy:
  -
    provider: NuGet
    api_key:
      secure: fLRrY6iKFQhPFD5fHraib6Ot+0x3eKiVWoBCiKT5zPRCqxWxLAycIO8lJWg3o43r
    artifact: NuGet_Files
    server:             # remove to push to NuGet.org
    skip_symbols: false
    symbol_server:      # remove to push symbols to SymbolSource.org
