pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 6.0.x SDK'
  inputs:
    packageType: sdk
    version: '6.0.x'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.4.0'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: 'Creating NuGet package (with debug symbols)'
  condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
  inputs:
    command: 'custom'
    projects: '**/AutoCAD.NET.Interop.20*.csproj'
    custom: 'msbuild'
    arguments: '/t:Pack'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: NuGetCommand@2
  displayName: 'Pushing NuGet package'
  condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.snupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'